name: vip_picnic
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_auth: ^3.4.2
  firebase_storage: ^10.3.4
  firebase_messaging: ^12.0.1
  cloud_firestore: ^3.4.2
  provider: ^6.0.3
  google_fonts: ^3.0.1
  pin_code_fields: ^7.4.0
  sliver_tools: ^0.2.7
  flutter_chat_bubble: ^2.0.0
  story_view: ^0.13.2
  flutter_switch: ^0.3.2
  get:
  email_validator: ^2.1.16
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  google_sign_in: ^5.4.0
  flutter_launcher_icons: ^0.9.3
  get_storage: ^2.0.3
  uuid: ^3.0.6
  firebase_dynamic_links: ^4.3.4
  share_plus: ^4.0.10+1
#  audioplayers: 0.18.1
  path_provider: ^2.0.11
  record_mp3: ^3.0.0
  cached_network_image: ^3.2.0
  permission_handler: 9.2.0
  flutter_local_notifications: ^9.7.1
  path_provider_android: ^2.0.19
  path_provider_ios: ^2.0.11
  photo_view: ^0.14.0
  url_launcher: ^6.1.5
  flutter_facebook_auth: ^4.4.1
  video_player: ^2.4.7
  chewie: ^1.3.4
  video_thumbnail: ^0.5.2
  video_compress: ^3.1.1
  flutter_uploader: ^3.0.0-beta.4
  shared_preferences: ^2.0.15
  shared_preferences_android: ^2.0.12
  shared_preferences_ios: ^2.1.1
  timeago: ^3.3.0
  intl_phone_field: ^3.1.0
  flutter_slidable:
  twilio_phone_verify: ^2.0.0
  dropdown_button2: 1.4.0
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.2
#  flutter_uploader: ^1.2.1
#  emoji_picker_flutter: ^1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    -  assets/images/


